### ISSUE TITLE
[feature]: multiple slots

### ISSUE THREAD

**Issue by bennypowers** [Simplr/simplr-router#18]
It would be cool if this router could render to named slots for a child. Instigating use case: a route that points to a `profile-page` component, which has an anonymous slot and a `sidebar` named slot.

straw UX:

```js
const routes = [{
  path: '/profile',
  component: 'profile-page',
  import: () => import('./components/profile'), 
  routes: [{
    path: '/',
    component: 'my-profile',
    slots: [{
      sidebar: 'my-friends',
      import: () => import('./components/friends-list'),
    }]
  }, {
    path: '/:userId',
    components: 'user-profile',
    slots: [{
      sidebar: 'my-friends',
      import: () => import('./components/friends-list'),
    }]
  }
}]
```

**Comment by Matsuuu** [comment]
Am I getting this right:

If the user navigates to `/profile/userId`, the router will return 
```html
<user-profile>
    <my-friends slot="sidebar"></my-friends>
</user-profile>
```

?

**Comment by bennypowers** [comment]
on the nose!

another example is "view-specific toolbars" from this @captaincodeman post (you'll have to translate from good-old polymer 2 syntax, but the concept holds)

https://www.captaincodeman.com/2017/09/08/beyond-the-polymer-starter-kit-dialogs-and-toolbars

**Comment by Matsuuu** [comment]
That sounds pretty easy to implement, and a useful addition!

I'll take a shot at this next week !

**Comment by Matsuuu** [comment]
Implemented and published in v. 5.3.0

Docs can be found at https://router.matsu.fi/recipes/slots
