### ISSUE TITLE
Change transition style

### ISSUE THREAD

**Issue by madeInLagny** [Simplr/simplr-router#27]
Thanks for this repo. Great job. How do we change page transition style ? I need a fade effect in my project

**Comment by Matsuuu** [comment]
Hey @madeInLagny , Nice to hear you're enjoying the repo.

I'll see into the ease of implementing a few different transition styles and allowing users to define their own ones.

I'll update here on the progress today

**Comment by Matsuuu** [comment]
Hey, @madeInLagny .

I've implemented custom transition, and it's released with the 5.6.0 patch to the package.

For docs, you can go to https://router.matsu.fi/recipes/transition-styling
and for an example you can see that [codesandbox](https://codesandbox.io/s/quirky-hill-330x0?fontsize=14&hidenavigation=1&theme=dark&file=/index.html)
