### ISSUE TITLE
Transition CSS does not apply to Shadow Dom ?

### ISSUE THREAD

**Issue by madeInLagny** [Simplr/simplr-router#29]
Hi, thanks for your recent update. I have implemented it in an open-wc project with lit-element. It looks like the CSS properties do not apply to shadow dom. The following code does not provide a fade-in-out transition

```
import { LitElement, css } from 'lit-element';
import SimplrRouter from '@simplr-wc/router';

export class AppShell extends LitElement {
  static get styles() {
    return css`
      simplr-router-container[entering-view],
      simplr-router-container[leaving-view] {
        opacity: 0;
      }
    `;
  }

  constructor() {
    super();
    const routes = [
      {
        path: '',
        component: 'hello-world',
        import: () => import('/views/testView/testView.js'),
      },
      {
        path: 'hello/:userName', // userName is accessible by testView.js as a property
        component: 'hello-world',
        import: () => import('/views/testView/testView.js'),
      },
    ];
    const router = new SimplrRouter({ routes, disableTransition: true });
    router.init();
  }
}

window.customElements.define('app-shell', AppShell);
```

**Comment by Matsuuu** [comment]
Hello,

The styles are meant to be applied on the DOM-level, meaning inside the index.html file, instead of inside shadow root, since the Simplr Router appends the containers at the bottom of the DOM also, instead of inside the shadow root.

So move the styles to the top level and try again :)

**Comment by madeInLagny** [comment]
Cool :) Thanks for your support.

**Comment by Matsuuu** [comment]
No problem. If this resolves the problem, do close this issue, but if more problems arise, you can ask about them here

**Comment by madeInLagny** [comment]
Just some food for thought. It would be interesting to:
* manage transitions at route level. You don't necessarily want the same
transition for all pages. I am thinking of landing/description pages that
could be fancy as opposed to contact or terms and conditions pages that
don't need anything. I looked at your guard option, but it looks like it
either redirects to a forbidden or a not found page.
* listen to an event that would fire before the page loads. You could then
make some checks and redirect to another url if need be. For instance, the
first segment of my pwa url contains a locale. I could check if that locale
fits the user browser settings and redirect if not.

Cheers.

**Comment by Matsuuu** [comment]
Thanks for the feedback!

Custom transitions might not be the main focus for now, mostly due to the fact that you would need to actively inject css on the page.

I'm planning on implementing a middleware system to allow the kind of features your seconds prompt asked for
