### ISSUE TITLE
How do the sub routes works?

### ISSUE THREAD

**Issue by hanc2006** [Simplr/simplr-router#35]
Hi,
I'm trying to apply this example to a real world, but it doesn't seem to work. What should happen when I write http://www.mysite.com/user/110? What I expect is:

1. load component home
2. load component user (inside a default `<slot></slot>` in home)
3. load component user-profile (inside a default `<slot></slot>` in user)

![image](https://user-images.githubusercontent.com/4517251/120107906-1b5dfe80-c163-11eb-8a3a-7607a7d57c6a.png)

```
const routes = [
  {
    path: "/",
    component: "home",
    routes: [
      {
        path: "user",
        component: "user-view",
        routes: [
          {
            path: ":userId",
            component: "user-profile",
            routes: [
              {
                path: "edit",
                component: "user-profile-edit"
              }
            ]
          }
        ]
      }
    ]
  }
];
```

But what happens is that only the user-profile component is loaded, so i can't understand how the nested routes works.

**Comment by Matsuuu** [comment]
Documentation about the sub routes explains that they are mostly to avoid repetition https://router.matsu.fi/recipes/sub-routes

What you are trying to achieve is documented in the slots -section https://router.matsu.fi/recipes/slots

**Comment by hanc2006** [comment]
Thank you,
I finally have a working example, but I have some questions:

Is it possible to create more nested slots (or only one level)?
When I switch from one view to another, the whole tree is reloaded (the parent component too), it's right?

I created this sandbox for reference: https://codesandbox.io/s/admiring-colden-v7ct2?file=/src/index.js

**Comment by Matsuuu** [comment]
Yeah Simplr Router is sort of a "Dumb" router in a sense that it doesn't really limit the developer, and required the developer to work out the kinks. Making a clear rule that something is re-loaded and something isn't would be something out of scope for a simple router. 

As for the nested slots. When the slots idea was introduced as requested in https://github.com/Simplr/simplr-router/issues/18 , I didn't come to think about wanting to have nested slots there. 

If that is a feature that you see would add value, I could look into adding it in the following week. Is that something that would benefit you?

**Comment by Matsuuu** [comment]
hey @hanc2006  :) Pinging you again to check how you're progressing, and if this feature is urgent for your project?

I've been quite busy lately but I'm sure I could squeeze this one out within a week

**Comment by hanc2006** [comment]
Hey @Matsuuu, sorry for the delay, but I was busy the last week. Don't worry, I finally choose another way, one simple router that react on push state change. Thanks for your interest :+1:
