### ISSUE TITLE
Write a test suite

### ISSUE THREAD

**Issue by Matsuuu** [Simplr/simplr-router#50]
As the router has gone through another round of development, a new test suite would be in order.

It should be built with the web test runner and focus on testing the routing recipes, outlet and view actions, and maybe for visual regression

**Comment by pmcelhaney** [comment]
Once the test runner is set up I may be able to help with building out tests.

**Comment by Matsuuu** [comment]
That would be grand!

**Comment by heybran** [comment]
Is cypress a good option to test spa router?

**Comment by Matsuuu** [comment]
Hi @heybran .

I'm working on sunsetting this project as we've written a more versatile router here: https://github.com/Simplr/suunta

For that router, I've used Web Test Runner to write the unit tests for
