### ISSUE TITLE
this.staticRoutes is not iterable

### ISSUE THREAD

**Issue by nik-christou** [Simplr/simplr-router#51]
Hello, I tried to use the latest version from npm v7.0.0-rc-7 and I got the below error:

![image](https://user-images.githubusercontent.com/38988084/141755135-1fb74cff-4fa2-4436-8e29-76aca0126db8.png)

Note: I am using snowpack but it should not matter cause other similar router projects I tested they seem to work.

**Comment by nik-christou** [comment]
Never mind - I just re-installed the library and it worked. My apologies for opening a bug.

**Comment by Matsuuu** [comment]
Glad that it worked out :) 

Let me know if there's other stuff you run into
