### ISSUE TITLE
Load child route/component into parent route/component <slot>

### ISSUE THREAD

**Issue by nik-christou** [Simplr/simplr-router#52]
Hello,

Is it possible to load child route/component into the <slot> element of the parent route ?

I know that we can use the <slot> element to define a dynamic component however this will not work in case multiple child route/components use the same parent. I will try to have a look at the source code to see if this is possible. 

This is the only missing piece before switching from vaading-router :-)

**Comment by Matsuuu** [comment]
Heya  @nik-christou ,

is this the kind of functionality you mean? https://router.vuejs.org/guide/essentials/nested-routes.html

If so, it's not yet implemented. I've been thinking of implementing this, if there's need for this and if this is indeed the case, I'll start work on it ASAP

**Comment by nik-christou** [comment]
Thank you for the quick reply. Yes I believe Vue router has the same functionality as in vaadin-router "Nested Components" 
 https://vaadin.github.io/router/vaadin-router/demo. 
For my use case its the only thing missing.

**Comment by Matsuuu** [comment]
Heya,

I hacked around some and made the first round of implementations on the nested routes. They should function as per the docs page here: https://simplr.github.io/simplr-router/guides/recipes/nested-routes/

Go ahead and try it out and give some feedback. They are released in the latest release candidate

**Comment by nik-christou** [comment]
Thanks Matsuuu, the new feature works as expected. This router has a lot of potential - it just ticks the right boxes. :-)

**Comment by Matsuuu** [comment]
Glad to hear! I hope it gets adopted more so I can iterate on it and make it better
