### ISSUE TITLE
Fire an event when new location url has changed

### ISSUE THREAD

**Issue by nik-christou** [Simplr/simplr-router#53]
I have a use case where I would like to be notified when a location change has occurred so I can proceed with some computation based on the new url/pathname. 

I tried to use event listeners on window.location for 'hashchange' or 'popstate' but I did not get any events. I noticed that there is a 'getCurrentView' function available but this is not event. 

Ideally I would like to either add an event listener on the  SimplrRouter._instance to be notified about the new view or maybe a custom event is fired from the window object so its available without import.

I see that we can add a middleware to the instance but from what I understand those are meant to add functionality to the router functionality and not to get notified when the location has changed. 

Any ideas how I can get notified about the new location url ?

**Comment by Matsuuu** [comment]
Heya,

There actuall is [some events that get fired as navigation happens](https://github.com/Simplr/simplr-router/blob/master/lib/modules/dispatcher.js#L1-L3) but looking at it, they are quite outdated.

I'll take a look at them tonight and try to time them better and provide more information.

Are there other cases you would want to listen to than "url changed" ?

**Comment by nik-christou** [comment]
Basically I have a list of links and I am trying to figure out which link to style as selected based on the currently loaded view. 
The dispatcher sendEvent function is it called after history is updated ?

**Comment by Matsuuu** [comment]
Currently it's called _after_ it is called.

I'm thinking of adding a "simplr-router-history-updated" -event that gets dispatched AFTER the history has been updated. You could then plug into that

**Comment by nik-christou** [comment]
That sounds great. I just checked vaadin router is doing something similar. It fires an custom event 'vaadin-router-location-changed' and you can attach a window event listener from any web component.

**Comment by Matsuuu** [comment]
Yeah that's exactly what I was planning on doing. I'll try to get it pushed out today. I'll inform you about it as I publish it. 

If some other events come to mind that might be of use, let me know.

In the mean time... You can also get the current view data using the API of simplr router

```javascript
import { getCurrentView } from "@simplr-wc/router";

getCurrentView();
```

**Comment by Matsuuu** [comment]
The latest Release candidate (rc9) will contain an event called `simplr-router-navigated` which triggers in window scope when a navigation has finished and updated the history of the page.

You can read more about it here https://simplr.github.io/simplr-router/docs/api/events/

**Comment by nik-christou** [comment]
This works as expected. Thanks for the releasing so fast 👍
