### ISSUE TITLE
Exclude paths for static assets

### ISSUE THREAD

**Issue by nik-christou** [Simplr/simplr-router#55]
In my project I have icons and other files that are mounted to a specific path "/assets/icons" so no matter where I define a link the "src" will always start with this path followed by the file name and extension. 

If I add such a link under a nested view the parent view path gets added as a prefix for example if I am in the child view "managers" under "users" parent view the link becomes like this: "users/managers/assets/icons/icons1.png" instead of "/assets/icons/icons1.png". This fails to load because such a resource does not exist.

Is it possible to instruct the router to skip these links or maybe to exclude routing for specific paths ?

**Comment by Matsuuu** [comment]
Heya,

Yeah it's completely possible. Could you produce a minimal example of this, either in a repo of your own or a code sandbox so I can debug it ?

**Comment by nik-christou** [comment]
Yes of course I will try to prepare a small demo this weekend.

**Comment by nik-christou** [comment]
So I managed to find the issue and it was not the router but rather my snowpack configuration. I am trying to use shoelace and static assets need to be mounted. In any case thanks for the time but we can close this ticket since nothing is wrong with the router.
